// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdcexJ18xq7n7TI7KHjbZ_cpaimPAGgY',
    appId: '1:18272534744:web:de4b859e219cfea68497ad',
    messagingSenderId: '18272534744',
    projectId: 'itsanotetaking-flutter-proj',
    authDomain: 'itsanotetaking-flutter-proj.firebaseapp.com',
    storageBucket: 'itsanotetaking-flutter-proj.appspot.com',
    measurementId: 'G-CW2L4BDBZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkn5IV6F3uV34EDL1BrLqsRx1f3G_FEng',
    appId: '1:18272534744:android:bf24d86266b2399b8497ad',
    messagingSenderId: '18272534744',
    projectId: 'itsanotetaking-flutter-proj',
    storageBucket: 'itsanotetaking-flutter-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cJPHmEdVO4Ry6ylkhdoWKXxHN7QQ8BI',
    appId: '1:18272534744:ios:86367c1272925a548497ad',
    messagingSenderId: '18272534744',
    projectId: 'itsanotetaking-flutter-proj',
    storageBucket: 'itsanotetaking-flutter-proj.appspot.com',
    iosClientId: '18272534744-mmoenbq2hspelqb7db7jaln32si4vodk.apps.googleusercontent.com',
    iosBundleId: 'com.appsandroidfortesting.takemynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cJPHmEdVO4Ry6ylkhdoWKXxHN7QQ8BI',
    appId: '1:18272534744:ios:94036259a325cb448497ad',
    messagingSenderId: '18272534744',
    projectId: 'itsanotetaking-flutter-proj',
    storageBucket: 'itsanotetaking-flutter-proj.appspot.com',
    iosClientId: '18272534744-4lhppp84t8s0u9ilk9kbui9dcnhdrbg9.apps.googleusercontent.com',
    iosBundleId: 'com.appsandroidfortesting.takemynotes.RunnerTests',
  );
}
